import {copy,statusLabels,workflows} from '../data/mockData';import {useTask} from '../hooks/useWorkbench';import {Panel} from '../components/Panel';import {StatusBadge} from '../components/StatusBadge';
interface TasksPageProps {readonly demo?:boolean;}
import {WorkflowInputs} from '../components/WorkflowInputs';
export function TasksPage(_:TasksPageProps){const task=useTask();return <><div className="page-heading"><div><h1>{copy.taskTitle}</h1><p>{copy.taskIntro}</p></div><StatusBadge status={task.run.status}/></div>
 <Panel className="mb-5"><label htmlFor="workflow">{copy.workflowLabel}</label><select id="workflow" className="workflow-input block mt-3 mb-3" value={task.definition.id} onChange={task.select} disabled={task.active}>{workflows.map(w=><option key={w.id} value={w.id}>{w.name}</option>)}</select><p>{task.definition.description}</p><p>{copy.workflowVersion}{copy.separator}{task.definition.version}</p><WorkflowInputs definition={task.definition} run={task.run} onChange={task.changeInput} incomplete={task.missing.length>0}/><p className="mt-3">{copy.selectionHint}</p></Panel>
 <div className="flex flex-wrap gap-3 mb-6">{task.actions.map(a=><button className="button primary" key={a} onClick={task.act.bind(null,a)} disabled={a==='start'&&task.missing.length>0}>{copy.taskActions[a]}</button>)}</div>
 {task.run.status==='waiting-approval'&&<Panel title={copy.approvalTitle} className="mb-5 approval"><p>{task.definition.steps[task.run.cursor].approval}</p><h3 className="mt-3">{copy.boundInputs}</h3><dl>{task.definition.inputs.map(name=><div key={name}><dt>{name}</dt><dd className="break-words">{task.run.inputs[name]}</dd></div>)}</dl></Panel>}
 <p className="mb-5">{copy.recoveryNotice}</p>
 <div className="grid lg:grid-cols-[3fr_2fr] gap-5"><Panel><ol className="timeline">{task.definition.steps.map((s,i)=><li key={s.id} aria-current={task.active&&i===task.run.cursor?'step':undefined}><span className="step-number">{i+1}</span><span>{s.label}</span><StatusBadge status={task.run.steps[i]}/></li>)}</ol></Panel>
 <Panel title={copy.logTitle}><div role="log" aria-live="polite" className="font-mono text-sm space-y-3">{task.run.events.length?task.run.events.map((event,i)=><p key={i}>{String(i+1).padStart(2,'0')}{copy.separator}{task.definition.steps.find(s=>s.id===event.stepId)?.label}{copy.separator}{statusLabels[event.status]}{copy.separator}{copy.demoOnly}</p>):<p>{copy.noEvents}</p>}</div></Panel></div></>;}
